language: php

php:
- 7.1
- 7.2

before_script:
  - pecl channel-update pecl.php.net
  - pecl install mailparse
  - composer self-update
  - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
