language: php

php:
- 7.3
- 7.4snapshot

jobs:
  allow_failures:
  - php: 7.4snapshot

before_script:
  - pecl channel-update pecl.php.net
  - pecl install mailparse
  - composer self-update
  - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
