language: php

php:
  - 5.6
  - 7.0

before_script:
  - pecl channel-update pecl.php.net
  - pecl install mailparse
  - composer self-update
  - composer install --no-interaction

script: ./vendor/bin/phpunit
