language: php

php:
  - 5.6

before_script:
  - pecl channel-update pecl.php.net
  - pecl install -f mailparse-2.1.6
  - composer self-update
  - composer install --no-interaction

script: ./vendor/bin/phpunit
