language: php

matrix:
  include:
    - php: 5.6
      env: EXT_MAILPARSE_VER="-f mailparse-2.1.6"
    - php: 7.0
      env: EXT_MAILPARSE_VER="mailparse"

before_script:
  - pecl channel-update pecl.php.net
  - pecl install $EXT_MAILPARSE_VER
  - composer self-update
  - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
